server:
  port: 9090

spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: test-realm.json
